name: Releas

on: 
  push:
    tags:
    - '\d+\.\d+\.\d+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name:
      run: |
        ./build.sh
        git add dist/
        VERSION="${GITHUB_REF/ref\/tags\//}"
        git commit -m "v${VERSION}"
        git tag --force "${VERSION}"
        git push --force --tags
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/list.txt"
        token: ${{ secrets.GITHUB_TOKEN }}

