name: Releas

on: 
  push:
    tags:
    - '\d+\.\d+\.\d+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir dist
        cp index.js dist/
        tar -czvf dist.tar.gz dist/*
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          dist.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

