name: Releas

on: 
  push:
    tags:
    - '\d+\.\d+\.\d+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        echo "create dist"
        mkdir dist
        ls -la dist
        echo "dist created"
        echo "copy index.js"
        cp index.js dist/
        ls -la dist
        cat dist/index.js
        echo "index.js copied"
        echo "create dist.tar.gz"
        tar -czvf dist.tar.gz dist/*
        ls -la dist.tar.gz
        tar -ztvf dist.tar.gz
        echo "dist.tar.gz created"
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          dist.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

