name: Releas

on: 
  push:
    tags:
    - '\d+\.\d+\.\d+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name:
      run: |
        ./build.sh
        #git add dist/
        #version="${GITHUB_REF/ref\/tags\//}"
        #git commit -m "v${version}"
        #git tag "v${version}"
        #git push --tags
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/list.txt"
        #tag: ""
        token: ${{ secrets.GITHUB_TOKEN }}

